export const TEAMS = [
  // ── Group A ──────────────────────────────────────────────────────────────────
  { code: 'ARG', isoCode: 'ar',     name: 'Argentina',    flag: '🇦🇷', group: 'A', color: '#75AADB', players: ['Lionel Messi', 'Julián Álvarez', 'Rodrigo De Paul', 'Ángel Di María', 'Emiliano Martínez', 'Nicolás Otamendi', 'Alexis Mac Allister', 'Thiago Almada', 'Lautaro Martínez', 'Enzo Fernández', 'Paulo Dybala', 'Germán Pezzella', 'Nahuel Molina', 'Marcos Acuña', 'Leandro Paredes', 'Guido Rodríguez'] },
  { code: 'POL', isoCode: 'pl',     name: 'Poland',       flag: '🇵🇱', group: 'A', color: '#DC143C', players: ['Robert Lewandowski', 'Piotr Zieliński', 'Wojciech Szczęsny', 'Jakub Moder', 'Jan Bednarek', 'Kamil Glik', 'Arkadiusz Milik', 'Bartosz Bereszyński', 'Matty Cash', 'Karol Linetty', 'Sebastian Szymański', 'Przemysław Frankowski', 'Jakub Kiwior', 'Adam Buksa', 'Kamil Piątek', 'Michał Skóraś'] },
  { code: 'ECU', isoCode: 'ec',     name: 'Ecuador',      flag: '🇪🇨', group: 'A', color: '#FFD100', players: ['Enner Valencia', 'Moisés Caicedo', 'Piero Hincapié', 'Gonzalo Plata', 'Michael Estrada', 'Jeremy Sarmiento', 'Ángel Mena', 'Diego Palacios', 'Jackson Porozo', 'Pervis Estupiñán', 'Byron Castillo', 'Jhegson Méndez', 'Romario Ibarra', 'Alan Minda', 'Roberto Ordóñez', 'John Yeboah'] },
  { code: 'QAT', isoCode: 'qa',     name: 'Qatar',        flag: '🇶🇦', group: 'A', color: '#8B0000', players: ['Hassan Al-Haydos', 'Almoez Ali', 'Akram Afif', 'Bassam Al-Rawi', 'Homam Ahmed', 'Abdulaziz Hatem', 'Assim Madibo', 'Boualem Khoukhi', 'Ismaeel Mohammad', 'Ali Asadalla', 'Khalid Muneer', 'Meshaal Barsham', 'Tariq Salman', 'Abdulkarim Hassan', 'Karim Boudiaf', 'Ahmed Al-Rawi'] },
  // ── Group B ──────────────────────────────────────────────────────────────────
  { code: 'ENG', isoCode: 'gb-eng', name: 'England',      flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', group: 'B', color: '#CF091F', players: ['Harry Kane', 'Jude Bellingham', 'Bukayo Saka', 'Jordan Pickford', 'Kyle Walker', 'John Stones', 'Declan Rice', 'Phil Foden', 'Marcus Rashford', 'Raheem Sterling', 'Luke Shaw', 'Reece James', 'Trent Alexander-Arnold', 'Mason Mount', 'Ollie Watkins', 'Cole Palmer'] },
  { code: 'IRN', isoCode: 'ir',     name: 'Iran',         flag: '🇮🇷', group: 'B', color: '#239F40', players: ['Mehdi Taremi', 'Sardar Azmoun', 'Alireza Jahanbakhsh', 'Ali Gholizadeh', 'Saman Ghoddos', 'Ehsan Hajsafi', 'Majid Hosseini', 'Ramin Rezaeian', 'Saeid Ezatolahi', 'Morteza Pouraliganji', 'Ali Beiranvand', 'Shojae Khalilzadeh', 'Karim Ansarifard', 'Ahmad Nourollahi', 'Milad Mohammadi', 'Omid Noorafkan'] },
  { code: 'USA', isoCode: 'us',     name: 'USA',          flag: '🇺🇸', group: 'B', color: '#3C3B6E', players: ['Tyler Adams', 'Christian Pulisic', 'Gio Reyna', 'Weston McKennie', 'Matt Turner', 'Sergiño Dest', 'Yunus Musah', 'Ricardo Pepi', 'Folarin Balogun', 'Brendan Aaronson', 'Tim Weah', 'Antonee Robinson', 'Walker Zimmerman', 'Miles Robinson', 'DeAndre Yedlin', 'Malik Tillman'] },
  { code: 'WAL', isoCode: 'gb-wls', name: 'Wales',        flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿', group: 'B', color: '#C8102E', players: ['Gareth Bale', 'Aaron Ramsey', 'Daniel James', 'Kieffer Moore', 'Ben Davies', 'Neco Williams', 'Joe Allen', 'Ethan Ampadu', 'Brennan Johnson', 'Wayne Hennessey', 'Chris Mepham', 'Connor Roberts', 'Matthew Smith', 'Dylan Levitt', 'Mark Harris', 'Tyler Roberts'] },
  // ── Group C ──────────────────────────────────────────────────────────────────
  { code: 'FRA', isoCode: 'fr',     name: 'France',       flag: '🇫🇷', group: 'C', color: '#002395', players: ['Kylian Mbappé', 'Antoine Griezmann', 'Ousmane Dembélé', 'Mike Maignan', 'Jules Koundé', 'Raphaël Varane', 'Adrien Rabiot', 'Aurélien Tchouaméni', 'Eduardo Camavinga', 'Marcus Thuram', 'Randal Kolo Muani', 'Benjamin Pavard', 'Dayot Upamecano', 'Théo Hernández', 'William Saliba', 'Youssouf Fofana'] },
  { code: 'DEN', isoCode: 'dk',     name: 'Denmark',      flag: '🇩🇰', group: 'C', color: '#C60C30', players: ['Christian Eriksen', 'Pierre-Emile Højbjerg', 'Kasper Schmeichel', 'Simon Kjær', 'Joakim Mæhle', 'Andreas Christensen', 'Mikkel Damsgaard', 'Yussuf Poulsen', 'Thomas Delaney', 'Alexander Bah', 'Victor Nelsson', 'Rasmus Højlund', 'Jonas Wind', 'Jesper Lindstrøm', 'Robert Skov', 'Mathias Jensen'] },
  { code: 'TUN', isoCode: 'tn',     name: 'Tunisia',      flag: '🇹🇳', group: 'C', color: '#E70013', players: ['Wahbi Khazri', 'Youssef Msakni', 'Hannibal Mejbri', 'Ellyes Skhiri', 'Naïm Sliti', 'Ali Maâloul', 'Montassar Talbi', 'Mohamed Drager', 'Anis Ben Slimane', 'Dylan Bronn', 'Seifeddine Jaziri', 'Mohamed Ali Ben Romdhane', 'Ferjani Sassi', 'Fakhreddine Ben Youssef', 'Hamza Rafia', 'Nizar Issaoui'] },
  { code: 'CRC', isoCode: 'cr',     name: 'Costa Rica',   flag: '🇨🇷', group: 'C', color: '#002B7F', players: ['Keylor Navas', 'Bryan Ruiz', 'Joel Campbell', 'Kendall Waston', 'Bryan Oviedo', 'Oscar Duarte', 'Christian Gamboa', 'Celso Borges', 'Ronald Matarrita', 'Yeltsin Tejeda', 'Anthony Contreras', 'Warren Madrigal', 'Francisco Calvo', 'Johan Venegas', 'Alonso Martínez', 'Jurgen Damm'] },
  // ── Group D ──────────────────────────────────────────────────────────────────
  { code: 'GER', isoCode: 'de',     name: 'Germany',      flag: '🇩🇪', group: 'D', color: '#464646', players: ['Manuel Neuer', 'Joshua Kimmich', 'Toni Kroos', 'Florian Wirtz', 'Kai Havertz', 'Ilkay Gündogan', 'Leroy Sané', 'Thomas Müller', 'Niklas Süle', 'Antonio Rüdiger', 'Serge Gnabry', 'Jamal Musiala', 'David Raum', 'Nico Schlotterbeck', 'Chris Führich', 'Jonas Hofmann'] },
  { code: 'JPN', isoCode: 'jp',     name: 'Japan',        flag: '🇯🇵', group: 'D', color: '#BC002D', players: ['Takumi Minamino', 'Kaoru Mitoma', 'Daichi Kamada', 'Wataru Endō', 'Hiroki Sakai', 'Maya Yoshida', 'Shuichi Gonda', 'Ao Tanaka', 'Junya Itō', 'Takehiro Tomiyasu', 'Ko Itakura', 'Ritsu Dōan', 'Yuki Soma', 'Hayao Kawabe', 'Ayase Ueda', 'Gaku Shibasaki'] },
  { code: 'ESP', isoCode: 'es',     name: 'Spain',        flag: '🇪🇸', group: 'D', color: '#AA151B', players: ['Unai Simón', 'Dani Carvajal', 'Aymeric Laporte', 'Pau Torres', 'Jordi Alba', 'Rodri', 'Pedri', 'Gavi', 'Ferran Torres', 'Álvaro Morata', 'Marco Asensio', 'Dani Olmo', 'Fabián Ruiz', 'Mikel Merino', 'Lamine Yamal', 'Nico Williams'] },
  { code: 'BEL', isoCode: 'be',     name: 'Belgium',      flag: '🇧🇪', group: 'D', color: '#000000', players: ['Romelu Lukaku', 'Kevin De Bruyne', 'Thibaut Courtois', 'Jan Vertonghen', 'Toby Alderweireld', 'Yannick Carrasco', 'Leandro Trossard', 'Dries Mertens', 'Youri Tielemans', 'Thomas Meunier', 'Arthur Theate', 'Loïs Openda', 'Charles De Ketelaere', 'Axel Witsel', 'Amadou Onana', 'Johan Bakayoko'] },
  // ── Group E ──────────────────────────────────────────────────────────────────
  { code: 'BRA', isoCode: 'br',     name: 'Brazil',       flag: '🇧🇷', group: 'E', color: '#009C3B', players: ['Vinícius Jr.', 'Rodrygo', 'Marquinhos', 'Casemiro', 'Alisson', 'Thiago Silva', 'Neymar Jr.', 'Lucas Paquetá', 'Éder Militão', 'Raphinha', 'Bruno Guimarães', 'Fred', 'Danilo', 'Alex Telles', 'Endrick', 'Gabriel Martinelli'] },
  { code: 'SRB', isoCode: 'rs',     name: 'Serbia',       flag: '🇷🇸', group: 'E', color: '#C6363C', players: ['Dušan Vlahović', 'Aleksandar Mitrović', 'Sergej Milinković-Savić', 'Dušan Tadić', 'Filip Kostić', 'Nemanja Gudelj', 'Nikola Milenković', 'Vanja Milinković-Savić', 'Strahinja Pavlović', 'Ivan Ilić', 'Andrija Živković', 'Stefan Mitrović', 'Marko Grujić', 'Saša Lukić', 'Luka Ilić', 'Milan Gajić'] },
  { code: 'SUI', isoCode: 'ch',     name: 'Switzerland',  flag: '🇨🇭', group: 'E', color: '#FF0000', players: ['Granit Xhaka', 'Xherdan Shaqiri', 'Yann Sommer', 'Manuel Akanji', 'Silvan Widmer', 'Remo Freuler', 'Breel Embolo', 'Fabian Rieder', 'Noah Okafor', 'Kwadwo Duah', 'Nico Elvedi', 'Ricardo Rodríguez', 'Renato Steffen', 'Zeki Amdouni', 'Dan Ndoye', 'Edimilson Fernandes'] },
  { code: 'CMR', isoCode: 'cm',     name: 'Cameroon',     flag: '🇨🇲', group: 'E', color: '#007A5E', players: ['Vincent Aboubakar', 'André Onana', 'Eric Maxim Choupo-Moting', 'Karl Toko Ekambi', 'Jean-Charles Castelletto', 'Harold Moukoudi', 'Olivier Ntcham', 'André-Frank Zambo Anguissa', 'Samuel Gouet', 'Bryan Mbeumo', 'Collins Fai', 'Joyskim Dawa', 'Nicolas Nkoulou', 'Tolo Nouhou', 'Stéphane Bahoken', 'Martin Hongla'] },
  // ── Group F ──────────────────────────────────────────────────────────────────
  { code: 'POR', isoCode: 'pt',     name: 'Portugal',     flag: '🇵🇹', group: 'F', color: '#006600', players: ['Cristiano Ronaldo', 'Bruno Fernandes', 'Bernardo Silva', 'Rúben Dias', 'João Cancelo', 'Diogo Jota', 'Rafael Leão', 'Rúben Neves', 'Vitinha', 'João Félix', 'Pedro Neto', 'Gonçalo Inácio', 'Nuno Mendes', 'Diogo Dalot', 'William Carvalho', 'André Silva'] },
  { code: 'GHA', isoCode: 'gh',     name: 'Ghana',        flag: '🇬🇭', group: 'F', color: '#006B3F', players: ['Thomas Partey', 'André Ayew', 'Jordan Ayew', 'Mohammed Kudus', 'Alexander Djiku', 'Daniel Amartey', 'Baba Rahman', 'Tariq Lamptey', 'Daniel Afriyie Barnieh', 'Iñaki Williams', 'Joseph Aidoo', 'Jonathan Mensah', 'Abdul Salis Samed', 'Lawrence Ati-Zigi', 'Fatawu Issahaku', 'Antoine Semenyo'] },
  { code: 'URU', isoCode: 'uy',     name: 'Uruguay',      flag: '🇺🇾', group: 'F', color: '#5EB6E4', players: ['Luis Suárez', 'Edinson Cavani', 'Federico Valverde', 'Darwin Núñez', 'Ronald Araújo', 'José María Giménez', 'Rodrigo Bentancur', 'Nahitan Nández', 'Facundo Pellistri', 'Matías Vecino', 'Maxi Gómez', 'Gastón Pereiro', 'Sebastián Coates', 'Álvaro Dorda', 'Matías Olivera', 'Manuel Ugarte'] },
  { code: 'KOR', isoCode: 'kr',     name: 'South Korea',  flag: '🇰🇷', group: 'F', color: '#CD2E3A', players: ['Son Heung-min', 'Kim Min-jae', 'Lee Kang-in', 'Hwang Hee-chan', 'Cho Gue-sung', 'Jung Woo-young', 'Kim Young-gwon', 'Kim Jin-su', 'Kim Seung-gyu', 'Lee Jae-sung', 'Kwon Chang-hoon', 'Na Sang-ho', 'Jeong Woo-yeong', 'Hwang In-beom', 'Oh Hyeon-gyu', 'Kim Tae-hwan'] },
  // ── Group G ──────────────────────────────────────────────────────────────────
  { code: 'NED', isoCode: 'nl',     name: 'Netherlands',  flag: '🇳🇱', group: 'G', color: '#FF6600', players: ['Virgil van Dijk', 'Memphis Depay', 'Frenkie de Jong', 'Cody Gakpo', 'Stefan de Vrij', 'Denzel Dumfries', 'Xavi Simons', 'Davy Klaassen', 'Wout Weghorst', 'Teun Koopmeiners', 'Steven Bergwijn', 'Jeremie Frimpong', 'Jurrien Timber', 'Micky van de Ven', 'Ryan Gravenberch', 'Donyell Malen'] },
  { code: 'SEN', isoCode: 'sn',     name: 'Senegal',      flag: '🇸🇳', group: 'G', color: '#00853F', players: ['Edouard Mendy', 'Kalidou Koulibaly', 'Sadio Mané', 'Idrissa Gana Gueye', 'Cheikhou Kouyaté', 'Ismaïla Sarr', 'Abdou Diallo', 'Pape Matar Sarr', 'Nampalys Mendy', 'Famara Diédhiou', 'Boulaye Dia', 'Nicolas Jackson', 'Formose Mendy', 'Dion Lopy', 'Lamine Camara', 'Habib Diallo'] },
  { code: 'MEX', isoCode: 'mx',     name: 'Mexico',       flag: '🇲🇽', group: 'G', color: '#006847', players: ['Guillermo Ochoa', 'Hirving Lozano', 'Raúl Jiménez', 'Carlos Vela', 'Andrés Guardado', 'Héctor Herrera', 'Edson Álvarez', 'Jorge Sánchez', 'César Montes', 'Alexis Vega', 'Roberto Alvarado', 'Orbelin Pineda', 'Henry Martín', 'Jesús Gallardo', 'Gerardo Arteaga', 'Santiago Giménez'] },
  { code: 'KSA', isoCode: 'sa',     name: 'Saudi Arabia', flag: '🇸🇦', group: 'G', color: '#006C35', players: ['Salem Al-Dawsari', 'Mohammed Al-Owais', 'Yasser Al-Shahrani', 'Abdulelah Al-Malki', 'Sami Al-Najei', 'Firas Al-Buraikan', 'Ali Al-Bulaihi', 'Sultan Al-Ghanam', 'Hattan Bahebri', 'Mohamed Kanno', 'Saleh Al-Shehri', 'Nasser Al-Dawsari', 'Abdullah Al-Khaibari', 'Mohammed Al-Breik', 'Khalid Al-Ghannam', 'Riyadh Sharahili'] },
  // ── Group H ──────────────────────────────────────────────────────────────────
  { code: 'MAR', isoCode: 'ma',     name: 'Morocco',      flag: '🇲🇦', group: 'H', color: '#C1272D', players: ['Yassine Bounou', 'Achraf Hakimi', 'Romain Saïss', 'Sofyan Amrabat', 'Hakim Ziyech', 'Youssef En-Nesyri', 'Noussair Mazraoui', 'Nayef Aguerd', 'Azzedine Ounahi', 'Selim Amallah', 'Zakaria Aboukhlal', 'Abdelhamid Sabiri', 'Badr Benoun', 'Jawad El Yamiq', 'Ilias Chair', 'Sofiane Boufal'] },
  { code: 'CRO', isoCode: 'hr',     name: 'Croatia',      flag: '🇭🇷', group: 'H', color: '#E52B22', players: ['Luka Modrić', 'Ivan Perišić', 'Marcelo Brozović', 'Dejan Lovren', 'Joško Gvardiol', 'Mateo Kovačić', 'Ante Rebić', 'Bruno Petković', 'Mario Pašalić', 'Borna Sosa', 'Domagoj Vida', 'Nikola Vlašić', 'Martin Erlić', 'Josip Juranović', 'Andrej Kramarić', 'Lovro Majer'] },
  { code: 'CAN', isoCode: 'ca',     name: 'Canada',       flag: '🇨🇦', group: 'H', color: '#FF0000', players: ['Alphonso Davies', 'Jonathan David', 'Cyle Larin', 'Tajon Buchanan', 'Stephen Eustáquio', 'Atiba Hutchinson', 'Milan Borjan', 'Sam Adekugbe', 'Richie Laryea', 'Ismaël Koné', 'Jonathan Osorio', 'Lucas Cavallini', 'Marcus Godinho', 'Kamal Miller', 'Alistair Johnston', 'Liam Millar'] },
  { code: 'AUS', isoCode: 'au',     name: 'Australia',    flag: '🇦🇺', group: 'H', color: '#00843D', players: ['Mat Ryan', 'Harry Souttar', 'Mitchell Duke', 'Aaron Mooy', 'Mathew Leckie', 'Martin Boyle', 'Tom Rogic', 'Jackson Irvine', 'Ajdin Hrustic', 'Jason Cummings', 'Awer Mabil', 'Riley McGree', 'Miloš Degenek', 'Fran Karačić', 'Marco Tilio', 'Cameron Burgess'] },
  // ── Group I ──────────────────────────────────────────────────────────────────
  { code: 'ITA', isoCode: 'it',     name: 'Italy',        flag: '🇮🇹', group: 'I', color: '#003F87', players: ['Gianluigi Donnarumma', 'Alessandro Bastoni', 'Giovanni Di Lorenzo', 'Nicolò Barella', 'Davide Frattesi', 'Lorenzo Pellegrini', 'Federico Chiesa', 'Ciro Immobile', 'Giacomo Raspadori', 'Sandro Tonali', 'Mateo Retegui', 'Wilfried Gnonto', 'Destiny Udogie', 'Samuele Ricci', 'Giorgio Scalvini', 'Moise Kean'] },
  { code: 'COL', isoCode: 'co',     name: 'Colombia',     flag: '🇨🇴', group: 'I', color: '#FCD116', players: ['James Rodríguez', 'Luis Díaz', 'Juan Cuadrado', 'Davinson Sánchez', 'Yerry Mina', 'Wilmar Barrios', 'Mateus Uribe', 'Miguel Borja', 'Roger Martínez', 'Rafael Santos Borré', 'Cucho Hernández', 'Jhon Durán', 'Richard Ríos', 'Stefan Medina', 'Camilo Vargas', 'Carlos Cuesta'] },
  { code: 'NGA', isoCode: 'ng',     name: 'Nigeria',      flag: '🇳🇬', group: 'I', color: '#008751', players: ['Victor Osimhen', 'Alex Iwobi', 'Wilfred Ndidi', 'Ola Aina', 'William Troost-Ekong', 'Semi Ajayi', 'Taiwo Awoniyi', 'Frank Onyeka', 'Ahmed Musa', 'Calvin Bassey', 'Moses Simon', 'Bright Osayi-Samuel', 'Joe Aribo', 'Terem Moffi', 'Ademola Lookman', 'Kelechi Iheanacho'] },
  { code: 'NZL', isoCode: 'nz',     name: 'New Zealand',  flag: '🇳🇿', group: 'I', color: '#000000', players: ['Chris Wood', 'Winston Reid', 'Ryan Thomas', 'Liberato Cacace', 'Nando Pijnaker', 'Matthew Garbett', 'Bill Tuiloma', 'Joe Bell', 'Tim Payne', 'Marco Rojas', 'Tommy Smith', 'Clayton Lewis', 'Michael Boxall', 'Logan Rogerson', 'Alex Rufer', 'Mickel Miller'] },
  // ── Group J ──────────────────────────────────────────────────────────────────
  { code: 'TUR', isoCode: 'tr',     name: 'Turkey',       flag: '🇹🇷', group: 'J', color: '#E30A17', players: ['Hakan Çalhanoğlu', 'Arda Güler', 'Cengiz Ünder', 'Zeki Çelik', 'Çağlar Söyüncü', 'Merih Demiral', 'Mert Müldür', 'Kenan Yıldız', 'Barış Alper Yılmaz', 'Abdülkerim Bardakcı', 'Ferdi Kadıoğlu', 'Orkun Kökçü', 'Umut Meraş', 'Cenk Tosun', 'Altay Bayındır', 'Kaan Ayhan'] },
  { code: 'CIV', isoCode: 'ci',     name: "Côte d'Ivoire", flag: '🇨🇮', group: 'J', color: '#F77F00', players: ['Sébastien Haller', 'Nicolas Pépé', 'Franck Kessié', 'Wilfried Zaha', 'Simon Adingra', 'Serge Aurier', 'Eric Bailly', 'Ghislain Konan', 'Ibrahim Sangaré', 'Jean-Michaël Seri', 'Amad Diallo', 'Christian Kouamé', 'Willy Boly', 'Steeve Yago', 'Oumar Diakité', 'Jonathan Kodjia'] },
  { code: 'EGY', isoCode: 'eg',     name: 'Egypt',        flag: '🇪🇬', group: 'J', color: '#C8102E', players: ['Mohamed Salah', 'Mohamed Elneny', 'Ahmed Hegazi', 'Mostafa Mohamed', 'Omar Marmoush', 'Ramy Rabia', 'Ahmed Sayed Zizo', 'Marwan Hamdy', 'Hussein El-Shahat', 'Amr El-Sulaya', 'Omar Gaber', 'Ayman Ashraf', 'Hamdi Fathy', 'Mahmoud Alaa', 'Karim Fouad', 'Taher Mohamed Taher'] },
  { code: 'PAN', isoCode: 'pa',     name: 'Panama',       flag: '🇵🇦', group: 'J', color: '#DA121A', players: ['Rolando Blackburn', 'Adolfo Machado', 'Anibal Godoy', 'Alberto Quintero', 'Ismael Díaz', 'Cecilio Waterman', 'Armando Cooper', 'Fidel Escobar', 'Michael Murillo', 'Éric Davis', 'Abdiel Arroyo', 'José Rodríguez', 'Ricardo Ábrego', 'Tomás Martínez', 'Aníbal Godoy Jr.', 'Joel Ortiz'] },
  // ── Group K ──────────────────────────────────────────────────────────────────
  { code: 'AUT', isoCode: 'at',     name: 'Austria',      flag: '🇦🇹', group: 'K', color: '#ED2939', players: ['David Alaba', 'Marko Arnautovic', 'Marcel Sabitzer', 'Stefan Posch', 'Konrad Laimer', 'Christoph Baumgartner', 'Kevin Danso', 'Nicolas Seiwald', 'Patrick Wimmer', 'Michael Gregoritsch', 'Sasa Kalajdzic', 'Romano Schmid', 'Patrick Pentz', 'Maximilian Wöber', 'Florian Grillitsch', 'Stefan Ilsanker'] },
  { code: 'RSA', isoCode: 'za',     name: 'South Africa', flag: '🇿🇦', group: 'K', color: '#007A4D', players: ['Percy Tau', 'Lyle Foster', 'Ronwen Williams', 'Thulani Serero', 'Themba Zwane', 'Keagan Dolly', 'Bongani Zungu', 'Siyanda Xulu', 'Njabulo Ngcobo', 'Kermit Erasmus', 'Evidence Makgopa', 'Nkosinathi Sibisi', 'Yusuf Maart', 'Goodman Mosele', 'Terrence Mashego', 'Teboho Mokoena'] },
  { code: 'HON', isoCode: 'hn',     name: 'Honduras',     flag: '🇭🇳', group: 'K', color: '#0073CF', players: ['Romell Quioto', 'Anthony Lozano', 'Alberth Elis', 'Maynor Figueroa', 'Juan Pablo Montes', 'Jerry Bengtson', 'Edwin Rodríguez', 'Édder Delgado', 'Denil Maldonado', 'Javier Portillo', 'Carlos Discua', 'Luis López', 'Diego Rodríguez', 'Rony Martínez', 'Iván López', 'Wesly Decas'] },
  { code: 'IRQ', isoCode: 'iq',     name: 'Iraq',         flag: '🇮🇶', group: 'K', color: '#007A36', players: ['Ali Adnan', 'Amjad Attwan', 'Mohanad Ali', 'Aymen Hussein', 'Ahmed Ibrahim', 'Safaa Hadi', 'Saad Abdul Amir', 'Alaa Abbas', 'Bashar Resan', 'Mazin Abdulzahra', 'Ameen Al-Daho', 'Aziz Karim', 'Ali Jabbar', 'Humam Tariq', 'Zaid Tahseen', 'Alaa Abdulzehra'] },
  // ── Group L ──────────────────────────────────────────────────────────────────
  { code: 'SCO', isoCode: 'gb-sct', name: 'Scotland',     flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿', group: 'L', color: '#003087', players: ['Andy Robertson', 'Kieran Tierney', 'Scott McTominay', 'John McGinn', 'Callum McGregor', 'Stuart Armstrong', 'Ryan Christie', 'Kenny McLean', 'Ryan Porteous', 'Grant Hanley', 'Craig Gordon', 'Lyndon Dykes', 'Lawrence Shankland', 'Ryan Jack', 'Billy Gilmour', 'Lewis Ferguson'] },
  { code: 'VEN', isoCode: 've',     name: 'Venezuela',    flag: '🇻🇪', group: 'L', color: '#CF142B', players: ['Yeferson Soteldo', 'Yangel Herrera', 'Salomón Rondón', 'Darwin Machís', 'Tomás Rincón', 'Wuilker Fariñez', 'Jhon Murillo', 'Jefferson Savarino', 'José Martínez', 'Adrián Martínez', 'Sergio Córdova', 'Fernando Aristeguieta', 'Diego Rossi', 'Jhon Chancellor', 'Juanpi Añor', 'Cristian Cásseres Jr.'] },
  { code: 'JOR', isoCode: 'jo',     name: 'Jordan',       flag: '🇯🇴', group: 'L', color: '#007A3D', players: ['Yazan Al-Naimat', 'Musa Al-Taamari', 'Ahmad Hayel', 'Baha Faisal', 'Abdallah Nasib', 'Hamza Al-Dardour', 'Noor Ali Khashman', 'Ja\'far Al-Sawalmeh', 'Anas Bani Yaseen', 'Mahmoud Al-Mardi', 'Ehsan Haddad', 'Mofleh Al-Jarmi', 'Yazan Arab', 'Samer Awad', 'Salem Al-Ajarmeh', 'Montaser Talal'] },
  { code: 'ALG', isoCode: 'dz',     name: 'Algeria',      flag: '🇩🇿', group: 'L', color: '#006233', players: ['Riyad Mahrez', 'Islam Slimani', 'Youcef Atal', 'Sofiane Feghouli', 'Houssem Aouar', 'Said Benrahma', 'Ismael Bennacer', 'Andy Delort', 'Djamel Benlamri', 'Aissa Mandi', 'Haris Belkebla', 'Adam Ounas', 'Mohamed Amine Tougai', 'Ramiz Zerrouki', 'Baghdad Bounedjah', 'Amir Sayoud'] },
]

export const SPECIAL_STICKERS = [
  { id: 'SPEC-001', name: 'World Cup Trophy', rarity: 'legendary', emoji: '🏆' },
  { id: 'SPEC-002', name: 'WC 2026 Official Logo', rarity: 'rare', emoji: '🌍' },
  { id: 'SPEC-003', name: 'Official Match Ball', rarity: 'rare', emoji: '⚽' },
  { id: 'SPEC-004', name: 'MetLife Stadium', rarity: 'rare', emoji: '🏟️' },
  { id: 'SPEC-005', name: 'SoFi Stadium', rarity: 'rare', emoji: '🏟️' },
  { id: 'SPEC-006', name: 'Estadio Azteca', rarity: 'legendary', emoji: '🏟️' },
  { id: 'SPEC-007', name: 'Golden Boot', rarity: 'legendary', emoji: '👟' },
  { id: 'SPEC-008', name: 'Golden Glove', rarity: 'legendary', emoji: '🧤' },
  { id: 'SPEC-009', name: 'Top Scorer', rarity: 'legendary', emoji: '⭐' },
  { id: 'SPEC-010', name: 'Host Nations Trio', rarity: 'legendary', emoji: '🤝' },
]

export function generateTeamStickers(team) {
  const stickers = []
  stickers.push({ id: `${team.code}-BADGE`, teamCode: team.code, type: 'badge', rarity: 'rare', name: `${team.name} — Badge`, number: 0 })
  stickers.push({ id: `${team.code}-SQUAD`, teamCode: team.code, type: 'squad', rarity: 'rare', name: `${team.name} — Squad`, number: 0 })
  team.players.forEach((playerName, i) => {
    stickers.push({
      id: `${team.code}-P${String(i + 1).padStart(2, '0')}`,
      teamCode: team.code,
      type: 'player',
      rarity: i < 2 ? 'legendary' : i < 5 ? 'rare' : 'common',
      name: playerName,
      number: i + 1,
    })
  })
  return stickers
}

export const ALL_STICKERS = [
  ...TEAMS.flatMap(generateTeamStickers),
  ...SPECIAL_STICKERS.map((s) => ({ ...s, teamCode: 'SPEC', type: 'special' })),
]

export const RARITY_STYLES = {
  common: { border: 'border-slate-700', glow: '', bg: 'bg-slate-800/60', label: 'Common', labelColor: 'text-slate-400' },
  rare: { border: 'border-blue-500/60', glow: 'shadow-blue-500/20 shadow-lg', bg: 'bg-blue-950/40', label: 'Rare', labelColor: 'text-blue-400' },
  legendary: { border: 'border-amber-400/80', glow: 'shadow-amber-400/30 shadow-xl animate-pulse-gold', bg: 'bg-amber-950/40', label: 'Legendary', labelColor: 'text-amber-400' },
}
